### ISSUE TITLE
Cannot build on GNU/Linux : CMakeLists are missing (?)

### ISSUE THREAD

**Issue by valkheim** [avast-tl/retdec#68] opened 2017-12-22 21:06 UTC
Hi, I cannot build retdec following the README instructions. Apparenty, some CMakeLists are missing. I unsuccessfully tried to `git checkout tags/v3.0`
```
~/cq/retdec/build > cmake .. -DCMAKE_INSTALL_PREFIX=~/cq/retdec 2>&1 |xsel -ib
CMake Error at deps/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/capstone2llvmir

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/ctypes

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/demangler

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/fileformat

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/fnc-patterns

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:10 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/libdwarf

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/llvm

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/pdbparser

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:13 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/retdec-config

  does not contain a CMakeLists.txt file.


CMake Error at deps/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/valkheim/cq/retdec/deps/tl-cpputils

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/valkheim/cq/retdec/CMakeFiles/CMakeOutput.log".
```

Any idea ?

**Comment by Leseratte10** [comment] 2017-12-23 00:05
You did not checkout recursively as stated in the instructions.

**Comment by s3rvac** [comment] 2017-12-23 06:35
Hi. Yes, @Leseratte10 is correct. When cloning, you need to clone recursively to get the contents of all submodules, which contain the `CMakeLists.txt` files that you are currently missing. I suggest cloning the `master` branch as it has many bugfixes over the `v3.0` tag:
```
git clone --recursive https://github.com/avast-tl/retdec
```
I am closing this as a duplicate of #4.

**Closed by s3rvac** 2017-12-23 06:35 UTC
