### ISSUE TITLE
Name conflict with fileinfo from Leptonica

### ISSUE THREAD

**Issue by c-mauderer** [avast-tl/retdec#70] opened 2017-12-25 19:17 UTC
I have a (minor) problem: On my system I have leptonica installed (the image processing library). I tried to install retdec and had the problem that both provide a tool called `/usr/bin/fileinfo`.

It's not really a big problem because I can just use some prefix or temporary rename the tools. But for a number of Linux distribution that could be a problem if they want to provide retdec as a package.

A possible solution would be some other name like `retdecfileinfo`.

**Comment by s3rvac** [comment] 2017-12-26 06:52
Hi. Thank you for the report. Currently, it is not recommended to install RetDec directly into your system (e.g. `/usr`). One reason for this is that there may be name conflicts. We recommend installing RetDec into a dedicated directory in your home directory, and then appropriately adding e.g. `$HOME/projects/retdec/bin` into your `PATH`.

Nevertheless, it would indeed be better if our tools were named more uniquely. We will address this when modifying the build system so that RetDec supports system-wide installation.

**Comment by c-mauderer** [comment] 2017-12-26 08:58
Hello @s3rvac, thanks for the response. Great to hear that you will try to get some more unique naming in the future. Currently I have a system wide installation because I use an AUR package on Arch Linux (https://aur.archlinux.org/packages/retdec-git/). But maybe I'll switch to a local installation instead.

By the way: Thanks to all contributors and to Avast for providing that tool as open source software.

**Comment by s3rvac** [comment] 2017-12-26 10:27
> Currently I have a system wide installation because I use an AUR package on Arch Linux (https://aur.archlinux.org/packages/retdec-git/). But maybe I'll switch to a local installation instead.

The AUR package was created by one of our users and so we cannot provide any guarantees that it works. Until RetDec supports a system-wide installation, we suggest to perform a local installation.

**Comment by c-mauderer** [comment] 2017-12-26 10:56
Yes I know that AUR packages are created by users and not maintained by you. I already created a few for some other packages myself. But some of them are the first step to an official package (supported by the distribution).

I also reported this first to the packager and only when I noted that the name is used throughout your scripts, I reported it here. But like I said: It's not really a problem. A local installation with some prefix is a usable workaround. Users of retdec are most likely developers so that shouldn't be too much of a problem for anyone.

**Comment by mewmew** [comment] 2017-12-26 13:52
@c-mauderer Thanks for reporting this. Just to note, I uploaded the AUR package. So when a suggested resolution to the problem is presented, I'd be more than happy to include it. I'd personally prefer to limit the changes done to retdec by package distributions, as they will be harder to maintain. If the AUR package were to change the `fileinfo` name to `retdecfileinfo`, all scripts using this tool would also have to be updated, and the patches need to be kept in sync with the master branch. As such, it is probably better to wait until retdec renames the `fileinfo` tool, rather than maintaining local patches. Hope this makes sense, and doesn't create too much of an inconvenience for tesseract users (which has leptonica as a dependency).

**Comment by s3rvac** [comment] 2018-01-16 05:58
In the current `master`, we have renamed our tools so that they are all prefixed with `retdec-` (3ad168b01863491d96f5554e0bb9c770c2826442). For example, instead of `fileinfo`, we now have `retdec-fileinfo`.

This should resolve the reported name conflicts, so I am closing this issue.

**Closed by s3rvac** 2018-01-16 05:58 UTC
Labels: C-build-system, enhancement

**Comment by c-mauderer** [comment] 2018-01-16 08:08
Great. Thanks for that.
