### ISSUE TITLE
Could not acquire a cryptographic context: Unknown error (0x7F)

### ISSUE THREAD

**Issue by lab313ru** [avast-tl/retdec#73] opened 2017-12-30 15:10 UTC
File: https://www.emu-land.net/consoles/psx/emuls/linux?act=dlmfile&id=1047&fid=2
This is Playstation 1 emulator for Linux.
OS: Windows 10 x64.

**Comment by s3rvac** [comment] 2017-12-30 15:58
Hi. Could you please provide more context so we can investigate this?
* Did you use our binary release for Windows, or have you built RetDec by yourself?
* Do you use MSYS2 as suggested in our installation guide or something else (e.g. Cygwin, WSL)?
* Does decompilation of other files work correctly, or do you always get this error, no matter what the input file is?
* What parameters did you use when running `decompile.sh`?
* Most importantly, can you provide a full log from the decompilation and a ZIP archive with all files that the decompilation produced?

**Comment by lab313ru** [comment] 2017-12-30 17:12
1) I'm using b32 release for Windows;
2) MSYS2 32;
3) This error happens only for that file;
4) No additional params: just "decompile.sh pSX"
5) I've deleted every file, but now I'm started x64 version of the decompiler, and it stucked up, I guess, at this state: `-> running CopyPropagationOptimizer ( 151.32s )`.
So, you should try it to repeat my results.

**Comment by s3rvac** [comment] 2017-12-30 17:58
Thank you. Could you please also provide the complete output (log) from the decompilation which failed with `Could not acquire a cryptographic context: Unknown error`? Or do you at least know in which decompilation tool/phase it failed?

> it stucked up, I guess, at this state: -> running CopyPropagationOptimizer ( 151.32s ).

This phase often takes long time to finish, so you will either have to wait until it finishes or try to decompile only a part of the input binary file (as described e.g. [here](https://github.com/avast-tl/retdec/issues/13#issuecomment-352192225)).

**Comment by s3rvac** [comment] 2017-12-30 18:54
I was able to reproduce this issue (32b RetDec release, 64b MSYS2):
```
Warning: out of memory; trying to recover
Running phase: variable renaming [readable] ( 406.23s )
LLVM ERROR: Could not acquire a cryptographic context: The specified procedure could not be found.  (0x7F)
```
I strongly believe that this error is caused by insufficient memory.

**Comment by lab313ru** [comment] 2017-12-30 19:30
```
I strongly believe that this error is caused by insufficient memory.
```
I guess so... Because 64b version never printed this text out.

**Comment by s3rvac** [comment] 2017-12-31 06:57
Yes, the 64b version decompiles the file without any memory errors. 32b applications cannot allocate more than 2 or 4 GB of memory, depending on whether they were linked with [`/LARGEADDRESSAWARE`](https://msdn.microsoft.com/en-us/library/aa366778.aspx). I suggest using the 64b version of the decompiler as there is not much we can do with the 32b version.

**Comment by s3rvac** [comment] 2017-12-31 09:37
In commit 6003462ab9dd0e86b128a30aa96328a7d45170be, I have added the [`/LARGEADDRESSAWARE`](https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses) link flag to 32b builds of `bin2llvmir` and `llvmir2hll` so they can access up to 4 GB of virtual memory. I am closing this issue as there is probably nothing more we can do. When on 64b Windows, I recommend using the 64b build.

**Closed by s3rvac** 2017-12-31 09:37 UTC
Labels: C-retdec-llvmir2hll, O-windows, P-run
