### ISSUE TITLE
RetDec recognizes GCC 7.2.0 binaries as GCC 4.6.3

### ISSUE THREAD

**Issue by firmianay** [avast-tl/retdec#39] opened 2017-12-15 10:29 UTC
hi, I want to know if retdec on github and on online server have the different version. On my Arch Linux pc, gcc version is 7.2.0. And then, I try to decompile a binary.

This is the result from REST API:
```
// Detected compiler/packer: gcc (7.2.0)
```

and the result from my local build:
```
// Detected compiler/packer: gcc (4.6.3)
```
its wrong.

btw, the project is amazing!

**Comment by mbandzi** [comment] 2017-12-15 15:02
Hello,

I believe REST API uses some older stable version of RetDec so this is a possible regression as detections are currently under development. Could you please upload mentioned binary?

**Comment by s3rvac** [comment] 2017-12-15 18:59
@mbandzi We looked into this today for a bit with @metthal. There seems to be a regression with compiler detection. Consider the following file (32b ELF compiled with GCC 7.2.0 on Arch Linux): [hello-gcc-7.2.0.elf.zip](https://github.com/avast-tl/retdec/files/1563649/hello-gcc-7.2.0.elf.zip):

```
$ fileinfo -s hello-gcc-7.2.0.elf
[..]
Detected tool : GCC (4.6.3) RHEL (compiler), 27 from 49 significant nibbles (55.102%)
Detected tool : GCC (7.2.0) (compiler), .comment section heuristic
```

When decompiled, the JSON config `hello-gcc-7.2.0.c.json` contains

```
"tools" : [
   {
      "additional" : "RHEL",
      "heuristics" : false,
      "identicalSignificantNibbles" : 27,
      [..]
      "version" : "4.6.3"
   },
   {
      "heuristics" : true,
      [..]
      "version" : "7.2.0"
   }
],
```

When generating the _// Detected compiler/packer:_ comment, our back-end (`llvmir2hll`) chooses the first item from this list, so the compilers should be ordered by their priority.

We believe that there is a problem with the ordering of the detected compilers by their priority. In this case, the heuristic should probably have a greater priority than a signature having only 27/49 significant nibbles.

**Comment by mbandzi** [comment] 2017-12-19 13:04
fixed in master, thanks for the report

**Closed by mbandzi** 2017-12-19 13:04 UTC
Labels: bug
