### ISSUE TITLE
Can't decompile binary (mac-os) executable size: 25MB 

### ISSUE THREAD

**Issue by Karaulov** [avast-tl/retdec#235] opened 2018-03-05 06:25 UTC
Out of memory, and pc freeze and stop working....  (3.0 version from Releases, i can't download latest build from appveyor in artifacts)

Please if possible add plugin to fast 'zip' RAM memory (Using 20GB compressed to 2GB), for PC with smaller than 20GB RAM, or use temp file without RAM(I has a SSD and HDD pagefile, but retdec use both! And speed down...). Or this is impossible ?

![gtldnba 1](https://user-images.githubusercontent.com/6445336/36960642-fa623cf4-2058-11e8-8b1f-19bc12bf5e04.png)
![i7wcan6 1](https://user-images.githubusercontent.com/6445336/36960648-060220e2-2059-11e8-80c6-ebaef0c5a0dc.png)
![y7hfoky 1](https://user-images.githubusercontent.com/6445336/36960653-0f0c8470-2059-11e8-8515-09adc534b864.png)

(sorry bad english language)

**Comment by silverbacknet** [comment] 2018-03-05 09:08
Retdec never uses your pagefile; Windows does. You need to reconfigure your pagefile settings to remove it from D drive if you're seeing it used as a very slow page destination.

Aside from that, if you upgrade to Windows 10 then you'll automatically benefit from compressed memory, whereas it's a real bear to implement by individual developers. (OSX and most flavors of Linux also support it.)

**Comment by Karaulov** [comment] 2018-03-05 09:11
I have Windows 10. I tried to decompile various files, all require more than 10GB of RAM, but I do not have enough memory. Why does RetDec use more than 1GB of RAM for decompilation?

**Comment by s3rvac** [comment] 2018-03-05 13:02
Marking as a duplicate of #13.

**Closed by s3rvac** 2018-03-05 13:02 UTC
Labels: S-duplicate
