### ISSUE TITLE
"internal compiler error" when building capstone2llvmir

### ISSUE THREAD

**Issue by blacktop** [avast-tl/retdec#74] opened 2017-12-30 19:05 UTC
```bash
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/SystemZ/MCTargetDesc/SystemZMCCodeEmitter.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[5]: *** [lib/CodeGen/SelectionDAG/CMakeFiles/LLVMSelectionDAG.dir/FunctionLoweringInfo.cpp.o] Error 4
lib/CodeGen/SelectionDAG/CMakeFiles/LLVMSelectionDAG.dir/build.make:110: recipe for target 'lib/CodeGen/SelectionDAG/CMakeFiles/LLVMSelectionDAG.dir/FunctionLoweringInfo.cpp.o' failed
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[5]: *** [lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o] Error 4
lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/build.make:110: recipe for target 'lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o' failed
make[5]: *** Waiting for unfinished jobs....
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/SystemZ/TargetInfo/SystemZTargetInfo.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/AsmParser/X86AsmParser.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/AsmParser/X86AsmInstrumentation.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/MCTargetDesc/X86ELFObjectWriter.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[5]: *** [lib/IR/CMakeFiles/LLVMCore.dir/AutoUpgrade.cpp.o] Error 4
lib/IR/CMakeFiles/LLVMCore.dir/build.make:110: recipe for target 'lib/IR/CMakeFiles/LLVMCore.dir/AutoUpgrade.cpp.o' failed
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/MCTargetDesc/X86MCAsmInfo.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp.o
[ 36%] Building CXX object deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/TargetInfo/X86TargetInfo.cpp.o
deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/build.make:3422: recipe for target 'deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/AsmParser/X86AsmParser.cpp.o' failed
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/X86/AsmParser/X86AsmParser.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1148: recipe for target 'deps/capstone2llvmir/deps/keystone/llvm/keystone/CMakeFiles/keystone.dir/all' failed
CMakeFiles/Makefile2:927: recipe for target 'lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/all' failed
make[4]: *** [lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/all] Error 2
make[4]: *** [lib/CodeGen/SelectionDAG/CMakeFiles/LLVMSelectionDAG.dir/all] Error 2
CMakeFiles/Makefile2:839: recipe for target 'lib/CodeGen/SelectionDAG/CMakeFiles/LLVMSelectionDAG.dir/all' failed
CMakeFiles/Makefile2:500: recipe for target 'lib/IR/CMakeFiles/LLVMCore.dir/all' failed
make[4]: *** [lib/IR/CMakeFiles/LLVMCore.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
deps/capstone2llvmir/deps/llvm/CMakeFiles/llvm-project.dir/build.make:112: recipe for target 'external/src/llvm-project-stamp/llvm-project-build' failed
make[2]: *** [external/src/llvm-project-stamp/llvm-project-build] Error 2
CMakeFiles/Makefile2:1266: recipe for target 'deps/capstone2llvmir/deps/llvm/CMakeFiles/llvm-project.dir/all' failed
make[1]: *** [deps/capstone2llvmir/deps/llvm/CMakeFiles/llvm-project.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

building in ubuntu docker image with all the deps you listed in the README.

Thank you for opensourcing this amazing tool ❤️

**Comment by s3rvac** [comment] 2017-12-30 19:11
Hi. I believe that this is the same error as reported in #43 and #69. It is caused by insufficient memory in the system. I am closing this as a duplicate of the aforementioned issues.

**Closed** 2017-12-30 19:12 UTC
Labels: O-linux, P-build, S-duplicate
