### ISSUE TITLE
Clang Warnings on FreeBSD 

### ISSUE THREAD

**Issue by gwquk** [avast-tl/retdec#496] opened 2019-02-11 11:21 UTC
```
[ 21%] Building CXX object lib/MC/CMakeFiles/LLVMMC.dir/MCAssembler.cpp.o
In file included from /root/Downloads/devel/retdec/build/external/src/llvm-project/utils/TableGen/AsmWriterEmitter.cpp:16:
In file included from /root/Downloads/devel/retdec/build/external/src/llvm-project/utils/TableGen/CodeGenTarget.h:21:
In file included from /root/Downloads/devel/retdec/build/external/src/llvm-project/utils/TableGen/CodeGenRegisters.h:25:
In file included from /root/Downloads/devel/retdec/build/external/src/llvm-project/include/llvm/TableGen/Record.h:27:
In file included from /usr/include/c++/v1/map:442:
/usr/include/c++/v1/__tree:1819:22: warning: the specified comparator type does not provide a const call operator [-Wuser-defined-warnings]
                     __trigger_diagnostics()), "");
                     ^
/usr/include/c++/v1/__tree:876:70: note: in instantiation of member function 'std::__1::__tree<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > >::~__tree' requested here
    template <class, class, class> friend class _LIBCPP_TEMPLATE_VIS set;
                                                                     ^
/usr/include/c++/v1/memory:1595:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, void *> > >::__destroy<std::__1::pair<const std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > > >' requested here
            {__destroy(__has_destroy<allocator_type, _Tp*>(), __a, __p);}
             ^
/usr/include/c++/v1/__tree:1833:24: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, void *> > >::destroy<std::__1::pair<const std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > > >' requested here
        __node_traits::destroy(__na, _NodeTypes::__get_ptr(__nd->__value_));
                       ^
/usr/include/c++/v1/__tree:1821:3: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, std::__1::less<std::__1::basic_string<char> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > > > >::destroy' requested here
  destroy(__root());
  ^
/usr/include/c++/v1/map:736:77: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > >, std::__1::less<std::__1::basic_string<char> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char>, std::__1::set<std::__1::pair<llvm::CodeGenInstAlias, int>, (anonymous namespace)::AliasPriorityComparator, std::__1::allocator<std::__1::pair<llvm::CodeGenInstAlias, int> > > > > >::~__tree' requested here
    template <class, class, class, class> friend class _LIBCPP_TEMPLATE_VIS map;
                                                                            ^
/usr/include/c++/v1/__tree:970:7: note: from 'diagnose_if' attribute on '__trigger_diagnostics':
      _LIBCPP_DIAGNOSE_WARNING(!__invokable<_Compare const&, _Tp const&, _Tp const&>::value,
      ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__config:1130:20: note: expanded from macro '_LIBCPP_DIAGNOSE_WARNING'
    __attribute__((diagnose_if(__VA_ARGS__, "warning")))
                   ^           ~~~~~~~~~~~
```

**Comment by s3rvac** [comment] 2019-02-11 11:25
Hi. Isn't this a duplicate of #482? The following warning
```
warning: the specified comparator type does not provide a const call operator [-Wuser-defined-warnings]
```
should be already fixed in `master` (see #482).

**Comment by gwquk** [comment] 2019-02-11 11:58
Probably... I thought you had fixed the other warnings. Sorry!

**Comment by s3rvac** [comment] 2019-02-11 12:11
No problem. Let me know if you see any other warnings.

**Closed by s3rvac** 2019-02-11 12:11 UTC
Labels: C-llvm, O-bsd, P-build, T-comp-clang
