### ISSUE TITLE
IDA plugin refuses to decompile ("Decompilation is not properly configured")

### ISSUE THREAD

**Issue by 0x3FF8** [avast-tl/retdec#227] opened 2018-02-13 20:05 UTC
Hi,

retdec is working in command line (msys2) but with ida I have this fail

<img width="616" alt="capture d ecran 2018-02-13 a 20 53 00" src="https://user-images.githubusercontent.com/16087247/36171038-76e3f13a-1101-11e8-8522-6ea663a799b0.png">
<img width="454" alt="capture d ecran 2018-02-13 a 21 04 30" src="https://user-images.githubusercontent.com/16087247/36171057-84297892-1101-11e8-93e3-d4c533067f85.png">

How can I solve this problem? :)

thx,

**Comment by s3rvac** [comment] 2018-02-14 13:42
Hi. I think this issue belongs to the [retdec-idaplugin](https://github.com/avast-tl/retdec-idaplugin/issues) repository, but since you have already reported it here, let's discuss it ;-). Three questions:
* What RetDec version do you use? [v3.0](https://github.com/avast-tl/retdec/releases/tag/v3.0) or did you build your own version (e.g. from the current `master`)?
* What IDA plugin version do you use? [v0.4](https://github.com/avast-tl/retdec-idaplugin/releases/tag/v0.4) or did you build your own version (e.g. from the current `master`)?
* Does the `C:\retdec\bin\decompile.sh` file truly exist?

**Comment by 0x3FF8** [comment] 2018-02-15 07:45
Hi,

First:
I'm using retdec-v3.0-windows-32b.zip. (downloaded pre-compiled version)

Second:
I'm using retdec-idaplugin-v0.4-win.zip (downloaded pre-compiled version)

And yes the file path exists ;)

**Comment by PeterMatula** [comment] 2018-02-15 08:47
Hi,
just to be sure, what IDA version do you use? (It should be ok, since the plugin was loaded and you can configure it.)

Also, open `cmd.exe` and run `echo %Path%`. What does it print?

If you can run `decompile.sh` on your own, but it throws this error in IDA, then it looks like `decompile.sh` cannot be run from the plugin. In your case, run from the plugin should look like this:
```
std::system("sh 'C:\retdec\bin\decompile.sh' --help")
```
This should run it in `cmd.exe`. So can you try it in `cmd.exe` manually? Open `cmd.exe` and run command `sh 'C:\retdec\bin\decompile.sh' --help`. It should print RetDec's help. If it does not, then there is the problem - you need to add msys, or whatever has `sh`, to your system path.

**Comment by 0x3FF8** [comment] 2018-02-15 13:30
Hi,

I'm using IDA  6.8.150423

<img width="666" alt="capture d ecran 2018-02-15 a 14 28 14" src="https://user-images.githubusercontent.com/16087247/36258847-86cb0514-125c-11e8-9f60-b3cf1eefcbaa.png">

I don't understand why it's doesn't work in ida :(

**Comment by s3rvac** [comment] 2018-02-15 16:34
Would you be able to compile the following C program and run it in `cmd.exe` to see what it prints?
```c
#include <stdlib.h>
#include <stdio.h>

int main() {
    int rc = system("sh 'C:\\retdec\\bin\\decompile.sh' --help");
    printf("system() returned %d\n", rc);
    return 0;
}
```

**Comment by 0x3FF8** [comment] 2018-02-15 19:36
Hi, 

sh is not recognized ... but I don't understand why because it works in cmd

<img width="537" alt="capture d ecran 2018-02-15 a 20 34 39" src="https://user-images.githubusercontent.com/16087247/36276987-d5ef8ca4-128f-11e8-8838-e03013357f66.png">

**Comment by s3rvac** [comment] 2018-02-16 08:21
This is strange. What Windows version do you use? Could you now try to compile and run the following program in `cmd.exe`?
```c
#include <stdlib.h>

int main() {
    system("PATH");
    system("sh.exe --version");
    return 0;
}
```

**Comment by 0x3FF8** [comment] 2018-02-16 09:23
Hi,

the output 

<img width="654" alt="capture d ecran 2018-02-16 a 10 23 17" src="https://user-images.githubusercontent.com/16087247/36300935-76dcdce8-1303-11e8-8510-1212b49f5263.png">

**Comment by s3rvac** [comment] 2018-02-16 09:45
Alright. I see that the paths differ between `cmd.exe` and `system("set path")`, but I do not know why. Can you now run the following code and post its output?
```c
#include <stdlib.h>

int main() {
    system("set");
    return 0;
}
```

**Comment by 0x3FF8** [comment] 2018-02-16 09:55
Sure:  I don't know why to ! You are using windows ?

<img width="646" alt="capture d ecran 2018-02-16 a 10 54 56" src="https://user-images.githubusercontent.com/16087247/36302204-ee4b96d0-1307-11e8-9271-e67bef0c5371.png">

**Comment by 0x3FF8** [comment] 2018-02-16 10:17
Yup,

the 2 captures:
(right from cmd.exe)

<img width="1326" alt="capture d ecran 2018-02-16 a 11 16 22" src="https://user-images.githubusercontent.com/16087247/36303022-e72de21a-130a-11e8-9b00-8c2342bab38e.png">

**Comment by s3rvac** [comment] 2018-02-16 10:30
Are you sure the right one is from `set` run directly from `cmd.exe`? Because it seems to be the output from `test.exe` (and not `set`), and there is no `C:\msys64\usr\bin` in `Path` (see [this output](https://github.com/avast-tl/retdec/issues/227#issuecomment-365927565) from yesterday).

**Comment by s3rvac** [comment] 2018-02-16 10:39
Ah, I see. You ran `test.exe` outside of `cmd.exe` (left) and inside `cmd.exe` (right). Could you also try to run the `set` command in `cmd.exe`.

**Comment by 0x3FF8** [comment] 2018-02-16 10:40
Yes the left is from code block and the right windows is from cmd.exe maybe the var 
" set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH% " is removed automatically 

<img width="647" alt="capture d ecran 2018-02-16 a 11 39 14" src="https://user-images.githubusercontent.com/16087247/36303905-0ed7fc26-130e-11e8-818c-fdfdfe27e85c.png">

The .sh file are not interpreted in windows

**Comment by 0x3FF8** [comment] 2018-02-16 10:42
I have do the set path before in cmd.exe

**Comment by s3rvac** [comment] 2018-02-16 10:47
It seems to me that you did not add the following paths to you system `Path`, as per [our instructions on wiki](https://github.com/avast-tl/retdec/wiki/Windows-Environment#msys2-installation-and-configuration):

> Add the following path to the system PATH (if you already have Python installed, add the following after the path to Python):
> * 32-bit MSYS2: C:\msys32\usr\bin;C:\msys32\mingw32\bin
> * 64-bit MSYS2: C:\msys64\usr\bin;C:\msys64\mingw64\bin

[Here](https://www.computerhope.com/issues/ch000549.htm) is a HOWTO for different Windows versions. After you add the paths to your system path, can you try to run the IDA plugin again?

**Comment by 0x3FF8** [comment] 2018-02-16 10:52
So see I have already add the 2 MSYS2 32 and 64 bits file path:

<img width="641" alt="capture d ecran 2018-02-16 a 11 49 58" src="https://user-images.githubusercontent.com/16087247/36304376-b9bc477c-130f-11e8-9812-2c66135fcefc.png">

But it's doesn't work ! ...

**Comment by s3rvac** [comment] 2018-02-16 10:55
Yes, but you need to add the paths in Windows via _This PC_ -> _Properties_ -> _Advanced system settings_ -> _Environment Variables_ ([HOWTO](https://www.computerhope.com/issues/ch000549.htm)). It should look like this:

![windows-path](https://user-images.githubusercontent.com/5675953/36304520-43d3af36-1310-11e8-831c-326592a9fe75.png)

**Comment by 0x3FF8** [comment] 2018-02-16 11:05
Hmm,

It's correct ?  I have add:
Name:  Path64
Value:   C:\retdec\bin;C:\msys64\usr\bin;C:\msys64\mingw64\bin

![capture](https://user-images.githubusercontent.com/16087247/36304893-a9936dec-1311-11e8-92bf-2366f9fa1ecd.PNG)

**Comment by s3rvac** [comment] 2018-02-16 11:08
The paths should be added to `Path`, not to `Path32`/`Path64` (I think there are no such variables on Windows).

**Comment by s3rvac** [comment] 2018-02-16 11:19
The plugin works on both 32b and 64b Windows. Can you please paste the contents of _Valeur de la variable_ for `Path` in the _Modifier la variable systeme_ Windows dialog?

For example, my `Path` is
```
C:\Perl64\site\bin;C:\Perl64\bin;C:\Python3\;C:\Python3\Scripts;C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit
```
As you can see, it contains `C:\msys64\usr\bin;C:\msys64\mingw64\bin`. If you have `C:\msys64\usr\bin;C:\msys64\mingw64\bin` in there and the IDA plugin still does not work, as a last-resort solution, try rebooting your PC.

**Comment by 0x3FF8** [comment] 2018-02-16 13:18
Hmm, I'm sorry but it doesn't work on my computer. I think IDA can't start decompile.sh in MSYS2

I have try to add it and I have the same problem in IDA 👎 :(

You are using W8.1 (x86 or x64)? ( I can try to install an VM)

**Comment by s3rvac** [comment] 2018-02-16 13:27
We have successfully used our IDA plugin on the following Windows versions: 32b/64b Windows 7, 64b Windows 10, and 64b Windows Server 2012.

I still firmly believe that the problem is in that `C:\msys64\usr\bin;C:\msys64\mingw64\bin` is missing from your system `Path`. Could you please send me the value of your `Path` from the _Modifier la variable systeme_ Windows dialog (from [this one](https://user-images.githubusercontent.com/5675953/36304520-43d3af36-1310-11e8-831c-326592a9fe75.png))?

If the value of `Path` is correct and you have tried rebooting the PC, then I am afraid we cannot help you as we run out of ideas what might be wrong...

**Comment by 0x3FF8** [comment] 2018-02-16 13:32
Hi,

Hmm the file  C:\msys64\usr\bin; is here 

![capture](https://user-images.githubusercontent.com/16087247/36309720-0f0fd2f0-1326-11e8-9791-0ec95e20897c.PNG)

C:\msys64\mingw64\bin : 

![capture2](https://user-images.githubusercontent.com/16087247/36309761-3147fffa-1326-11e8-9dd8-978c8628082b.PNG)

**Comment by 0x3FF8** [comment] 2018-02-16 13:34
After reboot the problem is the same :@

**Comment by s3rvac** [comment] 2018-02-16 13:40
I think we do not understand each other. Let's try it this way:
* Right-click on _This PC_.
* Select _Properties_.
* Select _Advanced system settings_.
* Select _Environment Variables_.
* In the _System variables_ part, select and click on the `Path` variable, and then click on the _Edit_ button. You should now see [this](https://user-images.githubusercontent.com/5675953/36304520-43d3af36-1310-11e8-831c-326592a9fe75.png) window.
* Copy the text in _Variable value_ via Ctrl-C.
* Paste it here.

We just need to verify that your value of `Path` is correct.

**Comment by 0x3FF8** [comment] 2018-02-16 13:44
C:\Python30\;C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\

**Comment by s3rvac** [comment] 2018-02-16 16:11
The `Path` that you posted is correct. So, if the plugin still does not work, then I am sorry but we have no idea what else might be wrong :(. I guess that we will have to wait until there is another person with the same problem. Or maybe someone else will be able to help.

**Comment by s3rvac** [comment] 2018-03-06 14:36
I am closing this issue as we are unfortunately unable to reproduce the problem. If anyone who reads this is able to reproduce the problem, please open an issue in the [retdec-idaplugin](https://github.com/avast-tl/retdec-idaplugin/) repository and we will continue from there.

**Closed by s3rvac** 2018-03-06 14:36 UTC
Labels: C-retdec-idaplugin, O-windows, S-cannot-reproduce
