### ISSUE TITLE
Build Error on MacOS 10.11.6 (El Capitan)

### ISSUE THREAD

**Issue by newkit** [avast-tl/retdec#71] opened 2017-12-26 16:36 UTC
Hi, 

I am getting the following error when building on Mac OS El Capitan.
I Installed the required software in the required versions

```
# /usr/local/opt/flex/bin/flex --version
flex 2.6.4

# /usr/local/opt/bison/bin/bison --version
bison (GNU Bison) 3.0.4
```

I installed python 3 through homebrew and used the following line to ensure it is used:

```
# cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_LIBRARIES=/Library/Frameworks/Python.framework/Versions/3.4/lib/libpython3.4.dylib -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4
```

What maked my wonder, is the outdated flex version:
```
[ 62%] [FLEX][YaraLexer] Building scanner with flex 2.5.35
```

Someone had build under this rather old Mac OS version? Do I have to go with a newer one?

See the error log attached:
```
[ 61%] [BISON][YaraParser] Building parser with bison 3.0.4
[ 62%] [FLEX][YaraLexer] Building scanner with flex 2.5.35
Scanning dependencies of target yaramod
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/builder/yara_expression_builder.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/builder/yara_file_builder.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/builder/yara_hex_string_builder.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/builder/yara_rule_builder.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/parser/parser_driver.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/hex_string.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/literal.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/meta.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/cuckoo_module.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/dotnet_module.cpp.o
[ 62%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/elf_module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/hash_module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/magic_module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/math_module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/modules/pe_module.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/plain_string.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/rule.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/types/yara_file.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/utils/utils.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/yaramod.cpp.o
[ 63%] Building CXX object deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/yy_lexer.cpp.o
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:1026:9: error: no viable overloaded '='
                        yyin = & std::cin;
                        ~~~~ ^ ~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:197:20: note: candidate function not viable: no known conversion
      from 'istream *' (aka 'basic_istream<char> *') to 'std::__1::basic_istream<char>' for 1st argument; remove &
    basic_istream& operator=(basic_istream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:204:20: note: candidate function not viable: no known conversion
      from 'istream *' (aka 'basic_istream<char> *') to 'const std::__1::basic_istream<char>' for 1st argument; remove &
    basic_istream& operator=(const basic_istream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:1033:10: error: no viable overloaded '='
                        yyout = & std::cout;
                        ~~~~~ ^ ~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:174:20: note: candidate function not viable: no known conversion
      from 'ostream *' (aka 'basic_ostream<char> *') to 'std::__1::basic_ostream<char>' for 1st argument; remove &
    basic_ostream& operator=(basic_ostream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:180:20: note: candidate function not viable: no known conversion
      from 'ostream *' (aka 'basic_ostream<char> *') to 'const std::__1::basic_ostream<char>' for 1st argument; remove &
    basic_ostream& operator=(const basic_ostream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:1993:44: error: assigning to 'std::istream *' (aka 'basic_istream<char> *') from incompatible type
      'std::istream' (aka 'basic_istream<char>'); take the address with &
                        YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                                                                ^ ~~~~
                                                                  &
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2108:14: error: constructor for 'yyFlexLexer' must explicitly initialize the member 'yyin' which
      does not have a default constructor
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
             ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:32:25: note: expanded from macro 'yyFlexLexer'
    #define yyFlexLexer yyFlexLexer
                        ^
/usr/local/opt/flex/include/FlexLexer.h:171:16: note: member is declared here
  std::istream yyin;  // input source for default LexerInput
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:1728:48: note: 'std::__1::basic_istream<char>' declared here
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_TYPE_VIS basic_istream<char>)
                                               ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2108:14: error: field of type 'std::ostream' (aka 'basic_ostream<char>') has protected default
      constructor
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
             ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:32:25: note: expanded from macro 'yyFlexLexer'
    #define yyFlexLexer yyFlexLexer
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:222:5: note: declared protected here
    basic_ostream() {}  // extension, intentially does not initialize
    ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2110:7: error: no viable overloaded '='
        yyin = arg_yyin;
        ~~~~ ^ ~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:197:20: note: candidate function not viable: no known conversion
      from 'std::istream *' (aka 'basic_istream<char> *') to 'std::__1::basic_istream<char>' for 1st argument; dereference the argument with *
    basic_istream& operator=(basic_istream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:204:20: note: candidate function not viable: no known conversion
      from 'std::istream *' (aka 'basic_istream<char> *') to 'const std::__1::basic_istream<char>' for 1st argument; dereference the argument with *
    basic_istream& operator=(const basic_istream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2111:8: error: no viable overloaded '='
        yyout = arg_yyout;
        ~~~~~ ^ ~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:174:20: note: candidate function not viable: no known conversion
      from 'std::ostream *' (aka 'basic_ostream<char> *') to 'std::__1::basic_ostream<char>' for 1st argument; dereference the argument with *
    basic_ostream& operator=(basic_ostream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:180:20: note: candidate function not viable: no known conversion
      from 'std::ostream *' (aka 'basic_ostream<char> *') to 'const std::__1::basic_ostream<char>' for 1st argument; dereference the argument with *
    basic_ostream& operator=(const basic_ostream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2157:9: error: no viable overloaded '='
                yyout = new_out;
                ~~~~~ ^ ~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:174:20: note: candidate function not viable: no known conversion
      from 'std::ostream *' (aka 'basic_ostream<char> *') to 'std::__1::basic_ostream<char>' for 1st argument; dereference the argument with *
    basic_ostream& operator=(basic_ostream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:180:20: note: candidate function not viable: no known conversion
      from 'std::ostream *' (aka 'basic_ostream<char> *') to 'const std::__1::basic_ostream<char>' for 1st argument; dereference the argument with *
    basic_ostream& operator=(const basic_ostream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2161:21: error: out-of-line definition of 'LexerInput' does not match any declaration in
      'yyFlexLexer'
size_t yyFlexLexer::LexerInput( char* buf, size_t /* max_size */ )
                    ^~~~~~~~~~
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2166:11: error: member reference type 'std::istream' (aka 'basic_istream<char>') is not a pointer;
      did you mean to use '.'?
        if ( yyin->eof() || yyin->fail() )
             ~~~~^~
                 .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2166:26: error: member reference type 'std::istream' (aka 'basic_istream<char>') is not a pointer;
      did you mean to use '.'?
        if ( yyin->eof() || yyin->fail() )
                            ~~~~^~
                                .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2170:6: error: member reference type 'std::istream' (aka 'basic_istream<char>') is not a pointer;
      did you mean to use '.'?
        yyin->get( buf[0] );
        ~~~~^~
            .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2172:11: error: member reference type 'std::istream' (aka 'basic_istream<char>') is not a pointer;
      did you mean to use '.'?
        if ( yyin->eof() )
             ~~~~^~
                 .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2175:11: error: member reference type 'std::istream' (aka 'basic_istream<char>') is not a pointer;
      did you mean to use '.'?
        if ( yyin->bad() )
             ~~~~^~
                 .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2190:19: error: out-of-line definition of 'LexerOutput' does not match any declaration in
      'yyFlexLexer'
void yyFlexLexer::LexerOutput( const char* buf, size_t size )
                  ^~~~~~~~~~~
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2192:14: error: member reference type 'std::ostream' (aka 'basic_ostream<char>') is not a pointer;
      did you mean to use '.'?
        (void) yyout->write( buf, size );
               ~~~~~^~
                    .
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2557:37: error: non-const lvalue reference to type 'std::istream' (aka 'basic_istream<char>')
      cannot bind to a value of unrelated type 'std::istream *' (aka 'basic_istream<char> *')
        yy_init_buffer( YY_CURRENT_BUFFER, input_file );
                                           ^~~~~~~~~~
/usr/local/opt/flex/include/FlexLexer.h:156:58: note: passing argument to parameter 's' here
  void yy_init_buffer( yy_buffer_state* b, std::istream& s );
                                                         ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2608:7: error: no viable overloaded '='
        yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
        ~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:197:20: note: candidate function not viable: no known conversion
      from 'std::istream *' (aka 'basic_istream<char> *') to 'std::__1::basic_istream<char>' for 1st argument; dereference the argument with *
    basic_istream& operator=(basic_istream&& __rhs);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:204:20: note: candidate function not viable: no known conversion
      from 'std::istream *' (aka 'basic_istream<char> *') to 'const std::__1::basic_istream<char>' for 1st argument; dereference the argument with *
    basic_istream& operator=(const basic_istream& __rhs) = delete;
                   ^
/Users/nils/data/git/retdec/build/deps/fnc-patterns/deps/yaramod/src/yy_lexer.cpp:2641:21: error: non-const lvalue reference to type 'std::istream' (aka 'basic_istream<char>')
      cannot bind to a value of unrelated type 'std::istream *' (aka 'basic_istream<char> *')
        yy_init_buffer( b, file );
                           ^~~~
/usr/local/opt/flex/include/FlexLexer.h:156:58: note: passing argument to parameter 's' here
  void yy_init_buffer( yy_buffer_state* b, std::istream& s );
                                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/yy_lexer.cpp.o] Error 1
make[1]: *** [deps/fnc-patterns/deps/yaramod/src/CMakeFiles/yaramod.dir/all] Error 2
make: *** [all] Error 2

**Comment by s3rvac** [comment] 2017-12-26 18:38
Hi. I have no experience with macOS, but at least on Debian Linux, I know for sure that RetDec is buildable with
```
gcc   4.9.2
flex  2.5.39
bison 3.0.2
```
What compiler do you use for compilation? If Xcode, which version do you use?

**Comment by newkit** [comment] 2017-12-26 21:04
Thank you for you reply. It seems to be LLVM:

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
```

Xcode version 8.0: (8A218a)

I now had a private (local) installation directory under ~, but as you said, thats not related to my build issues. I wonder where this older flex version (2.5.35) get picked up when building yaramod.

**Comment by s3rvac** [comment] 2017-12-26 21:31
I remembered that about a year ago, I saw the error that you reported. It happened to one of our colleagues who used Linux (Ubuntu 14.04). The problem was solved by updating the `flex` and `libfl-dev` packages to the same version (2.6). The cause was an inconsistency in his system (`flex` 2.6 but `libfl-dev` 2.5).

I believe that you also have some inconsistency in your system as `/usr/local/opt/flex/bin/flex` reports version 2.6.4 but the version that is actually used during the build is 2.5.35. I would suggest to get rid of the 2.5.35 version so you have only 2.6 installed. Another option may be to try removing flex version 2.6 so you only have 2.5.35.

I am sorry I cannot assist you further as I have no idea how macOS packaging works (I only know that macOS users use Homebrew).

**Comment by newkit** [comment] 2017-12-29 07:42
Thanks for you advise and you time. Now it's getting wierd - I do not have flex 2.5.35 installed on my system. But thanks to your hint regarding libfl-dev I stumbled across this post

[http://linux-digest.blogspot.de/2013/01/using-flex-on-os-x.html](http://linux-digest.blogspot.de/2013/01/using-flex-on-os-x.html)

stateing that there is no libfl.a on Mac OS. The post suggests using libl.a instead.
Has anyone been able to successfully build on Mac OS or is it just an assumption, that it _should_work?

**Comment by s3rvac** [comment] 2017-12-30 08:45
> Now it's getting wierd - I do not have flex 2.5.35 installed on my system.

So CMake now correctly detects Flex 2.6.4?

> Has anyone been able to successfully build on Mac OS or is it just an assumption, that it _should_work?

We had a couple of PRs (e.g. https://github.com/avast-tl/retdec/pull/17) that add macOS build support, so we believe that RetDec should be buildable on macOS. Nevertheless, we have not yet been able to try macOS build ourselves (none of us uses macOS).

**Comment by newkit** [comment] 2017-12-31 14:31
I was able to build successfully. What I had overseen, that I still had the Apple flex and bison versions available which got picked up when building yaramod / scanner.

Since those files (`/usr/bin/flex` and `/usr/bin/bison`) are protected by Apples SIP (see [here](https://apple.stackexchange.com/questions/101328/file-cant-be-moved-by-root-on-os-x) if interested in details) they can't just simply be renamed. I had to boot into rescue mode (cmd + r) to rename those files. Then the newer flex and bison version get picked up correctly. Another (IMHO better) approach would be to fix the build scripts for yaramod in order to pick up the newer flex version. 

I realized that there is a small issue when running `install-share.sh` - it uses `sha256sum` which is `shasum -a 256`on Mac OS. Please see PR [#75](https://github.com/avast-tl/retdec/pull/75)

**Comment by stek29** [comment] 2018-01-01 06:47
README mentions that you need to export some variables to override apple's flex and bison. 
As of sha256sum -- good catch :)

**Comment by s3rvac** [comment] 2018-01-01 06:51
> I was able to build successfully.

Great!

> Another (IMHO better) approach would be to fix the build scripts for yaramod in order to pick up the newer flex version.

To find Flex and Bison, yaramod uses standard CMake's [`find_package()`](https://cmake.org/cmake/help/latest/command/find_package.html) command:

```
find_package(FLEX REQUIRED)
find_package(BISON REQUIRED)
```

The [documentation](https://cmake.org/cmake/help/latest/command/find_package.html) for `find_package()` lists several ways of overriding the search path, including setting `CMAKE_PREFIX_PATH`, `<package>_DIR`, or `PATH`.

> I realized that there is a small issue when running install-share.sh - it uses sha256sum which is shasum -a 256on Mac OS. Please see PR #75

Thank you. We will review the PR and will let you know.

**Comment by s3rvac** [comment] 2018-01-01 11:06
In cbd7685d31185a0d781028cfce24574feed07fc2, I have added `coreutils` into the list of required macOS packages (see #75), which should fix the installation on macOS.

I am closing this issue as I believe that all the problems were resolved. If not, feel free to reopen.

**Closed by s3rvac** 2018-01-01 11:06 UTC
Labels: D-help-wanted, O-macos, P-build
