### ISSUE TITLE
Compiling in os x

### ISSUE THREAD

**Issue by prokash** [avast-tl/retdec#49] opened 2017-12-19 02:57 UTC
I'm trying to compile the source on os x 10.13.

I got the cmake infrastructure using homebrew. Verified with standard tutorial that it works.

But when I try to do it on the downloaded source. I complains like this.

bash-3.2# pwd
/Users/admin/Downloads/retdec-master
bash-3.2# cmake -H. 
-- The CXX compiler identification is AppleClang 9.0.0.9000037
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CMake Error: The source directory "OUTPUT_VARIABLE" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CMakeTestCXXCompiler.cmake:30 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "/CMakeFiles/CMakeOutput.log".

Could someone provide some instructions about building it.
Thanks,
Prokash

**Comment by s3rvac** [comment] 2017-12-19 05:44
Closing as a duplicate of #7.

**Closed by s3rvac** 2017-12-19 05:44 UTC
Labels: duplicate
