### ISSUE TITLE
bin2llvmir crashes in "Control flow optimization" (Release) or on "Assertion `false' failed" (Debug)

### ISSUE THREAD

**Issue by Radu13** [avast-tl/retdec#97] opened 2018-01-18 17:45 UTC
[BOOT.zip](https://github.com/avast-tl/retdec/files/1643889/BOOT.zip)
Hello  i am trying to decompile a boot.bin file from psp game (it's an elf file), but check what gives me:
```
PS C:\Users\Radu\Desktop> bash C:/Users/Radu/Downloads/retdec/bin/decompile.sh BOOT.BIN
##### Checking if file is a Mach-O Universal static library...
RUN: /c/Users/Radu/Downloads/retdec/bin/macho-extractor --list /c/Users/Radu/Desktop/BOOT.BIN

##### Checking if file is an archive...
RUN: /c/Users/Radu/Downloads/retdec/bin/ar-extractor --arch-magic /c/Users/Radu/Desktop/BOOT.BIN
Not an archive, going to the next step.

##### Gathering file information...
RUN: /c/Users/Radu/Downloads/retdec/bin/fileinfo -c /c/Users/Radu/Desktop/BOOT.BIN.c.json --similarity /c/Users/Radu/Desktop/BOOT.BIN --no-hashes=all --crypto /c/Users/Radu/Downloads/retdec/bin/../share/generic/yara_patterns/signsrch/signsrch.yara
Input file               : C:/Users/Radu/Desktop/BOOT.BIN
File format              : ELF
File class               : 32-bit
File type                : Executable file
Architecture             : MIPS (MIPS I Architecture)
Endianness               : Little endian
Entry point address      : 0x8906934
Entry point offset       : 0x104ee8
Entry point section name : .text
Entry point section index: 2
Bytes on entry point     : e0ffbd270005023c0c00b3af21988000100044340800b2af2190a0000400b1af0000b0af0000103c1000bfafc837240e0000
Detected tool            : UPX (3.91 [LZMA]) (packer), 18 from 60 significant nibbles (30%)
Overlay offset           : 0x1d251a
Overlay size             : 0x2

##### Trying to unpack /c/Users/Radu/Desktop/BOOT.BIN into /c/Users/Radu/Desktop/BOOT.BIN-unpacked.tmp by using generic unpacker...
RUN: /c/Users/Radu/Downloads/retdec/bin/unpacker -d /c/Users/Radu/Downloads/retdec/bin/unpacker-plugins -o /c/Users/Radu/Desktop/BOOT.BIN-unpacked.tmp /c/Users/Radu/Desktop/BOOT.BIN
[ERROR] [UPX] Unsupported unpacking stub detected.
##### Unpacking by using generic unpacker: nothing to do

##### Trying to unpack /c/Users/Radu/Desktop/BOOT.BIN into /c/Users/Radu/Desktop/BOOT.BIN-unpacked.tmp by using UPX...
RUN: upx -d /c/Users/Radu/Desktop/BOOT.BIN -o /c/Users/Radu/Desktop/BOOT.BIN-unpacked.tmp
##### Unpacking by using UPX: nothing to do

##### Decompiling /c/Users/Radu/Desktop/BOOT.BIN into /c/Users/Radu/Desktop/BOOT.BIN.c.backend.bc...
RUN: /c/Users/Radu/Downloads/retdec/bin/bin2llvmir -provider-init -config-path /c/Users/Radu/Desktop/BOOT.BIN.c.json -decoder -disable-inlining -disable-simplify-libcalls -inst-opt -verify -volatilize -instcombine -reassociate -volatilize -control-flow -cfg-fnc-detect -main-detection -register -stack -control-flow -cond-branch-opt -syscalls -idioms-libgcc -constants -param-return -local-vars -type-conversions -simple-types -generate-dsm -remove-asm-instrs -select-fncs -unreachable-funcs -type-conversions -stack-protect -verify -instcombine -tbaa -targetlibinfo -basicaa -domtree -simplifycfg -domtree -early-cse -lower-expect -targetlibinfo -tbaa -basicaa -globalopt -mem2reg -instcombine -simplifycfg -basiccg -domtree -early-cse -lazy-value-info -jump-threading -correlated-propagation -simplifycfg -instcombine -simplifycfg -reassociate -domtree -loops -loop-simplify -lcssa -loop-rotate -licm -lcssa -instcombine -scalar-evolution -loop-simplifycfg -loop-simplify -aa -loop-accesses -loop-load-elim -lcssa -indvars -loop-idiom -loop-deletion -memdep -gvn -memdep -sccp -instcombine -lazy-value-info -jump-threading -correlated-propagation -domtree -memdep -dse -dce -bdce -adce -die -simplifycfg -instcombine -strip-dead-prototypes -globaldce -constmerge -constprop -instnamer -domtree -instcombine -never-returning-funcs -adapter-methods -class-hierarchy -instcombine -tbaa -targetlibinfo -basicaa -domtree -simplifycfg -domtree -early-cse -lower-expect -targetlibinfo -tbaa -basicaa -globalopt -mem2reg -instcombine -simplifycfg -basiccg -domtree -early-cse -lazy-value-info -jump-threading -correlated-propagation -simplifycfg -instcombine -simplifycfg -reassociate -domtree -loops -loop-simplify -lcssa -loop-rotate -licm -lcssa -instcombine -scalar-evolution -loop-simplifycfg -loop-simplify -aa -loop-accesses -loop-load-elim -lcssa -indvars -loop-idiom -loop-deletion -memdep -gvn -memdep -sccp -instcombine -lazy-value-info -jump-threading -correlated-propagation -domtree -memdep -dse -dce -bdce -adce -die -simplifycfg -instcombine -strip-dead-prototypes -globaldce -constmerge -constprop -instnamer -domtree -instcombine -simple-types -stack-ptr-op-remove -type-conversions -idioms -instcombine -global-to-local -dead-global-assign -instcombine -stack-protect -phi2seq -o /c/Users/Radu/Desktop/BOOT.BIN.c.backend.bc
Running phase: Initialization ( 0.01s )
Running phase: LLVM ( 0.01s )
Running phase: Providers initialization ( 0.01s )
Running phase: Input binary to LLVM IR decoding ( 0.12s )
Running phase: Assembly instruction optimization ( 8.58s )
Running phase: LLVM ( 8.70s )
Running phase: (Un)Volatilize optimization ( 8.95s )
Running phase: LLVM ( 9.09s )
Running phase: (Un)Volatilize optimization ( 10.48s )
Running phase: Control flow optimization ( 10.55s )
Wrote crash dump file "C:\Users\Radu\AppData\Local\Temp\bin2llvmir.exe-d015b4.dmp"
0x00007FF7C3AA16D1 (0x00000229D5E121B8 0x00000000088BA5BC 0x0000000000000000 0x00000000088BA5BC)
0x00007FF7C3B3E0A1 (0x00000000088BA5BC 0x00000000088BA5BC 0x00000229E22AC7F0 0x00000000088BA5BC)
0x00007FF7C3B40711 (0x0000022980428320 0x00000229D5E22240 0x0000000000000001 0x00000229D5DB0E18)
0x00007FF7C3B3E504 (0x0000000000000000 0x00000229D5E22240 0x0000000000000000 0x0000000000000000)
0x00007FF7C474B99F (0x0000022900000013 0x00000229D5DB0D40 0x0000000000000000 0x0000000000000000), log2() + 0x8E36BF bytes(s)
0x00007FF7C474B090 (0x00000229D77634D0 0x000000A44B34FC70 0x0000000000000000 0x00000229D77634D0), log2() + 0x8E2DB0 bytes(s)
0x00007FF7C3A8699A (0x0000000000000000 0x00007FF7C48C4D35 0x00007FFC300465D8 0x0000000000000416)
0x00007FF7C3A8A1C2 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7C48C54D9 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), log2() + 0xA5D1F9 bytes(s)
0x00007FFC32251FE4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFC33BAEFB1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
C:/Users/Radu/Downloads/retdec/bin/decompile.sh: line 900: 11676 Segmentation fault      $BIN2LLVMIR "${BIN2LLVMIR_PARAMS[@]}" -o "$OUT_BACKEND_BC"
Error: Decompilation to LLVM IR failed
```

I also insert boot.bin file (around 2MB size) if you want try it!
Thanks

**Comment by s3rvac** [comment] 2018-01-19 06:47
Thank you for the report. I can confirm that `bin2llvmir` crashes when decompiling the attached file `BOOT.bin` in the current `master` (60f7683aa8900245d606d777a2540e694cb0afbe).

Release build:
```
Running phase: Control flow optimization ( 8.92s )
retdec-decompiler.sh: line 900: 15875 Segmentation fault      "$BIN2LLVMIR" "${BIN2LLVMIR_PARAMS[@]}" -o "$OUT_BACKEND_BC"
```

Debug build:
```
Running phase: Input binary to LLVM IR decoding ( 0.17s )
retdec-bin2llvmir: include/retdec/capstone2llvmir/exceptions.h:150: retdec::capstone2llvmir::Capstone2LlvmIrError::Capstone2LlvmIrError(const string&): Assertion `false' failed.
retdec-decompiler.sh: line 900: 15064 Aborted                 "$BIN2LLVMIR" "${BIN2LLVMIR_PARAMS[@]}" -o "$OUT_BACKEND_BC"
```

**Comment by Radu13** [comment] 2018-01-19 09:37
Ok, i can do something about that or you can fix this issue someway?

**Comment by s3rvac** [comment] 2018-01-19 11:31
I am afraid you cannot do anything about this. We will fix the problem. There is an error during decoding (maybe an unsupported instruction).

**Comment by Radu13** [comment] 2018-01-19 12:18
Ok, when you fix it let me know! 😃

**Comment by MerovingianByte** [comment] 2018-01-19 17:27
Hopefully they'll start tackling memory issues soon :)

**Comment by Radu13** [comment] 2018-02-14 09:26
@s3rvac You solved the issue?

**Comment by s3rvac** [comment] 2018-02-14 09:52
@Radu13 Nope, the issue is still open.

**Comment by Radu13** [comment] 2018-02-22 12:23
Ok keep waiting for a fix then.

**Comment by Radu13** [comment] 2018-07-14 20:10
News?

**Comment by PeterMatula** [comment] 2018-07-16 07:35
I tested on 2 systems and this is not happening in the latest commit (386abd5). Pass `Control flow optimization` is no longer used, also the assertion @s3rvac mentioned is also no longer there.

Unfortunately the memory issues (#13, #16) @MerovingianByte mentioned are still not solved and this sample takes to much time and memory in `llvmir2hll`. It should not however crash on the issue mentioned here -> closing this, since the other problems are already reported. If it does not work for you, reopen.

**Closed by PeterMatula** 2018-07-16 07:35 UTC
Labels: C-bin2llvmir, P-run, bug
