### ISSUE TITLE
Several regression tests checking the presence of memset() fail on macOS

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#265] opened 2018-04-01 05:15 UTC
Several regression tests checking the presence of `memset()` in the decompiled code fail on macOS but succeed on Linux and Windows.

## Input

Run the following regression tests via [our testing framework](https://github.com/avast-tl/retdec-regression-tests-framework):
```
$ runner.py samples.bashbot
$ runner.py bugs.non-empty-decode -r 509262418069137b2d989f0ac2d1460f
$ runner.py features.avg-exotic-pe -r 074190bfb0a383539f695d885618fd54
$ runner.py bugs.idioms-reg-couples -r 0648a8d54b315eb2d3deb32b4a69909a
```

## Output

The tests fail:
```
samples.bashbot.BashbotTest (bashbot.arm.gcc.O0.elf -k)                        [ FAIL ]  (105.36s)
samples.bashbot.BashbotTest (bashbot.arm.gcc.O2.elf -k)                        [ FAIL ]  (182.54s)
samples.bashbot.BashbotTest (bashbot.arm.gcc.O3.elf -k)                        [ FAIL ]  (118.58s)
samples.bashbot.BashbotTest (bashbot.ppc.gcc.O0.elf -k)                        [ FAIL ]  (117.87s)
samples.bashbot.BashbotTest (bashbot.ppc.gcc.O2.elf -k)                        [ FAIL ]  (83.89s)
samples.bashbot.BashbotTest (bashbot.ppc.gcc.O3.elf -k)                        [ FAIL ]  (193.65s)
samples.bashbot.BashbotTest (bashbot.thumb.gcc.O0.elf -k)                      [ FAIL ]  (347.98s)
samples.bashbot.BashbotTest (bashbot.thumb.gcc.O1.elf -k)                      [ FAIL ]  (355.30s)
samples.bashbot.BashbotTest (bashbot.thumb.gcc.O3.elf -k)                      [ FAIL ]  (81.62s)
samples.bashbot.BashbotTest (bashbot.x86.gcc.O0.elf -k)                        [ FAIL ]  (116.25s)
samples.bashbot.BashbotTest (bashbot.x86.gcc.O1.elf -k)                        [ FAIL ]  (201.61s)
samples.bashbot.BashbotTest (bashbot.x86.gcc.O2.elf -k)                        [ FAIL ]  (63.01s)
samples.bashbot.BashbotTest (bashbot.x86.gcc.O3.elf -k)                        [ FAIL ]  (123.39s)
bugs.non-empty-decode.arm_elf_509262418069137b2d989f0ac2d1460f ([..])          [ FAIL ]  (79.81s)
features.avg-exotic-pe.Test_074190bfb0a383539f695d885618fd54 ([..])            [ FAIL ]  (8.43s)
bugs.idioms-reg-couples.TestCryptoLocker (0648a8d54b315eb2d3deb32b4a69909a -k) [ FAIL ]  (247.06s)
```

## Expected output

The tests should pass:
```
samples.bashbot.BashbotTest (bashbot.arm.gcc.O0.elf -k)                        [ OK ]  (105.36s)
...
```

## Notes

The tests fail with the following assertion (or similar):
```
======================================================================
FAIL: test_check_callgraph (samples.bashbot.BashbotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "retdec-regression-tests/samples/bashbot/test.py", line 156, in test_check_callgraph
    assert fnc.calls( 'memset' )
AssertionError
```
The decompiled code on Linux and macOS is identical or pretty similar, which suggests that there is an error when parsing the C code via our parser in the [regression-tests framework](https://github.com/avast-tl/retdec-regression-tests-framework). This could be due to different system include files on Linux and macOS.

## Configuration

* Commit: ae9a6d412caf73f1c93c7012a6f799de0cc95cdb (current `master`)
* 64b Arch Linux, GCC 7.3.1, Release build of RetDec
* mac OS 10.13, Apple LLVM version 9.0.0, Release build of RetDec

**Comment by PeterMatula** [comment] 2018-08-27 08:16
`memset` calls (or their variants) are present in the output C sources. The problem is that regression tests framework does not parse them correctly on macOS.

The first problem was that the call expression was parsed, but the name of called symbol was different from expected - it was some compiler intrinsic name derived from the original name. E.g. `memset` vs. `__builtin___memset_chk`. This was solved by name unification in regression test framework.

The second problem is when call expression is not parsed at all. See https://github.com/avast-tl/retdec-regression-tests-framework/issues/8 for more details.

This is not a problem in RetDec, but in regression tests, so I'm closing this issue.

**Closed by PeterMatula** 2018-08-27 08:16 UTC
Labels: C-regression-tests, O-macos, P-output, bug
