### ISSUE TITLE
cmake fails because all "deps" subfolders are empty

### ISSUE THREAD

**Issue by rfringuello89** [avast-tl/retdec#72] opened 2017-12-27 16:45 UTC
It is not possible to build RetDec because all "deps" subfolders are empty.

Steps:
- cd /opt/Programs/retdec/retdec/    (sources root)
- mkdir build && cd build
- cmake ../

Output:

> -- The CXX compiler identification is GNU 6.3.1
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Setting build type to 'Release' as none was specified.
> CMake Error at deps/CMakeLists.txt:1 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/capstone2llvmir
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:2 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/ctypes
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:3 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/demangler
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:4 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/fileformat
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:5 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/fnc-patterns
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:9 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/libdwarf
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:10 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/llvm
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:11 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/pdbparser
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:12 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/retdec-config
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at deps/CMakeLists.txt:13 (add_subdirectory):
>   The source directory
> 
>     /opt/Programs/retdec/retdec/deps/tl-cpputils
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/opt/Programs/retdec/retdec/build/CMakeFiles/CMakeOutput.log".

Here CMake output in attachment: 
[CMakeOutput.log](https://github.com/avast-tl/retdec/files/1589467/CMakeOutput.log)

**Comment by s3rvac** [comment] 2017-12-27 17:49
Hi. As stated in [Build and Installation](https://github.com/avast-tl/retdec#build-and-installation), you need to clone the repository recursively to get the contents of all submodules, which contain the `CMakeLists.txt` files that you are currently missing:
```
git clone --recursive https://github.com/avast-tl/retdec
```
If you have already cloned the repository, you can just run
```
git submodule update --init --recursive
```
I am closing this as a duplicate of #4 and #68.

**Closed** 2017-12-27 18:40 UTC
Labels: O-linux, P-build, S-duplicate
